### ISSUE TITLE
Question about module resolving

### ISSUE THREAD

**Issue by ceclin** [caoccao/Javet#130]
The V8Runtime#v8ModuleMap uses resourceName to identify IV8Module. For example: [V8Runtime#getV8Module](https://github.com/caoccao/Javet/blob/4d57f9063a3d0f52ad96a0aaa7050d073cf1e82c/src/main/java/com/caoccao/javet/interop/V8Runtime.java#L1286).

If my IV8ModuleResolver simply uses its paramater `resourceName` as modue's resource name (`setResourceName`) and two modules happen to use the same relative name to import their own submodules, the cached module loaded in the first module is returned to the second module.

Should I call setResourceName with resolved absolute name to avoid this situation? Is it expected?

**Comment by caoccao** [comment]
Your solution looks good to me.

Javet doesn't care about how to locate the modules. The internal module cache just covers a fundamental case. Advanced usage may leverage custom resource name and module mapping algorithm. Yours is an intuitive one. There could be some other solutions.

By the way, the more important goal of the internal module cache is to provide a baseline for preventing the resource leak from happening. With the internal module cache, applications don't need to explicitly close the modules because V8Runtime.close() takes care of that.
