### ISSUE TITLE
List<> as argument

### ISSUE THREAD

**Issue by PyXiion** [caoccao/Javet#180]
Hi, I'm back with stupid questions. I have a function that takes as an argument List<>, but it causes errors

Ok:
![Screenshot_20220809_183838](https://user-images.githubusercontent.com/59997570/183831373-319c8cfc-26d1-48a3-a3c5-3b1344318070.png)

Not ok:
![Screenshot_20220809_183932](https://user-images.githubusercontent.com/59997570/183831386-a4b2df1a-3c05-4fbd-ad57-1e60129de152.png)

Code:
![Screenshot_20220809_184045](https://user-images.githubusercontent.com/59997570/183831397-de4ab1c1-ec10-4e3f-9f9b-e76ebba96a60.png)

Maybe I need to turn on some setting?

**Comment by caoccao** [comment]
You need to remove `main` from global scope then call GC.

```java
v8Runtime.getGlobalObject().delete("main");
v8Runtime.lowMemoryNotification();
```

**Comment by PyXiion** [comment]
I mean List is not iterating

**Comment by caoccao** [comment]
That seems to be a bug. The workaround is to change the signature from `List` to `ArrayList`.

**Comment by PyXiion** [comment]
Thanks

**Comment by caoccao** [comment]
Actually, that is a feature in the proxy mode.

# Root Cause

`List` is an interface which is polyfilled by `JavetProxyConverter` with the JS counterpart. However, in your case it is a JS array which doesn't have the `hasNext()`.

# Options

## 1. Use ArrayList Instead

As `ArrayList` is not an interface, `JavetProxyConverter` will convert the JS array to the Java `ArrayList` and there will be no problem.

## 2. Polyfill the List

Provide a JS object which polyfills the `List`. E.g.

```js
main.execute({
  iterator: {
    index: 0,
    hasNext: () => index < 2,
    next: () => {
      if (index == 0) return 'a';
      if (index == 1) return 'b';
      if (index < 2) index++;
    }
  }
});
```

Please refer to this [commit](https://github.com/caoccao/Javet/commit/09b8fa45a4d5c9c5d0f8242b15e713e0e1c853ce) for detail.

**Comment by caoccao** [comment]
It has been fixed by this [commit](https://github.com/caoccao/Javet/commit/de30b9268fd9f32e51011ac3778b4af413ef6bd9) and will be included in the next release.
