### ISSUE TITLE
Default converter changes numerical string keys in JSON maps into numbers

### ISSUE THREAD

**Issue by ceggert87** [caoccao/Javet#183]
Hello there,

I hope the title does not sound too confusing - examples follow! 
In essence, whenever providing a JSON containing an object that has keys defined as string, but that contain numbers (e.g. "JSON.parse("{\"4000488011\": \"test\"}")", these seem to be turned into numbers when using the default object converter. This can cause problems down the line due to introducing E-notations.

Example code:
```      
V8Host.getV8Instance().createV8Runtime<V8Runtime>().use { v8Runtime ->
    val scriptResult = v8Runtime.getExecutor("JSON.parse(\"{\\\"4000488011\\\": \\\"test\\\"}\")").execute<V8ValueObject>()
    val result = v8Runtime.converter.toObject<Any>(scriptResult)
    Log.d("V8Test", result.toString())
    } 
```
With the result:
V8Test: {4.000488011E9=test}

This switch seems to happen in the native call for the V8Runtime's get method:
![image](https://user-images.githubusercontent.com/58487707/183899174-e64418a4-947e-48da-98d6-9c8606a0e70d.png)

Is this an actual bug that can be fixed or am I just unaware of something that would solve this problem?

This happens in both the latest 1.0.x version as well as the latest 1.1.x version

Thanks!

**Comment by caoccao** [comment]
Thank you for reporting this issue. It's a bug or not a bug depending on how you expect that to be.

V8 stores numeric keys as `number` internally and `number` can be 32bit or 64bit. In your case, the number is greater than `2**31 - 1` which is `2147483647`, so that it is stored as a 64bit number which is a `Double` in Java.

However, there are multiple ways of converting a Java `Double` to `String`. The scientific notation format is the default behavior (`Double.toString()`) which is the one in your case. Actually, if you try to use it as a key to access that object, V8 allows you to do so. So, it's not a solid bug. E.g.

```js
> const a = {'2147483648': 'x'}
undefined
> a
{ '2147483648': 'x' }
> a[2.147483648E9]
'x'
```

As the scientific notation presents poor readability, your ask is reasonable. This [commit](https://github.com/caoccao/Javet/commit/93db90bb64440d77b84e3f09694916b9c62037ae) was pushed to the dev branch to make that more readable. It'll be included in the next release. Please let me know if you have any questions.

**Comment by ceggert87** [comment]
Thanks for the explanation and solution @caoccao , that looks great!

Unless I'm misunderstanding things, this also has influence on actual usage, though. The use-case I experienced this in is basically a setup where data is fed from a database, which happens to have some items that have only numbers and go into this scientific notation range, which are then accessed by another external input. As the result of the default object converter is a HashMap form String to String, all information that it used to be a double is lost at that point.
If I see it correctly, this results from the JavetObjectConverter using "key.toString()" which would be fixed with your commit. Could this be considered a bugfix so that it makes its way into the 1.0.x release chain in that case? I suppose I can get this fixed by writing a custom converter, but it might surprise others as well.

Thanks for the quick response 👍

**Comment by caoccao** [comment]
Sure, Javet is very open in this case. I'm glad that you found a way.

v1.0.x has been deprecated for quite long. I wonder what are the benefits from patching and release a legacy branch, or why would you like to use v1.0.x. For Android ABI 21-22?

**Comment by ceggert87** [comment]
> For Android ABI 21-22?

Exactly, we still need to support API 21 devices. It works as expected with the converter change though, so for me personally it's fine like that. Thanks!
