### ISSUE TITLE
Mac OS X

### ISSUE THREAD

**Issue by ivanooi** [caoccao/Javet#24]
Hi,

 Any plan to support Mac OS? 

Thanks

**Comment by caoccao** [comment]
Good question.

I wrote this FAQ [Can Javet Support Mac?](https://github.com/caoccao/Javet/blob/main/docs/faq/can_javet_support_mac.rst) when I started this project. So far, I have no plan on purchasing a decent Mac device in the near future.

I wonder if someone else could work on that, or anyone could donate one to me.

**Comment by Cormanz** [comment]
@caoccao Is it possible for you to use some sort of VM for this?

**Comment by caoccao** [comment]
> @caoccao Is it possible for you to use some sort of VM for this?

I seriously doubt there might be slight difference. Some Intel NUC boxes supports MacOS and I have a pretty decent one. However, that only resolves x86-64. I haven't heard any news on VM for arm64.

Also, I think 2 Mac Mini boxes (x86-64 + arm64) might be quite ideal in terms of the ROI. I believe if the demand was so high, some organizations would donate me these assets. At least, I don't have plan to purchase them in few years (mainly for financial reason).

**Comment by Cormanz** [comment]
Oh, I see. Well you've already done a lot of great work in supporting Windows and Linux, and before I was going to use GraalJS, but seeing how Javet uses V8 directly, I plan to use it instead. Your work is very promising, thank you for working on Javet like this!

**Comment by caoccao** [comment]
> Oh, I see. Well you've already done a lot of great work in supporting Windows and Linux, and before I was going to use GraalJS, but seeing how Javet uses V8 directly, I plan to use it instead. Your work is very promising, thank you for working on Javet like this!

Good choice, and thank you.

From architectural perspective, GraalJS might impress people in PoC, but keep surprising the development team in production environment, simply because evil hides in details. There could be thousands of tiny inconsistencies between GraalJS and V8. These annoying things would drain the development resource and cause serious outages from time to time. Going with the authentic V8 is the right decision to make, I think.

**Comment by caoccao** [comment]
Updated: I think a virtual macos environment (VPS) may also work.

**Comment by caoccao** [comment]
Hi Folks,

My MacBook mid-2012 was revived with Mac OS Catalina which is the lowest version supported by latest V8. I managed to have built [snapshot version (x86_64) only](https://drive.google.com/drive/folders/18wcF8c-zjZg9iZeGfNSL8-bxqJwDZVEL?usp=sharing) for testing purpose. However, this won't last long because next time V8 abandons Catalina, I won't be able to create any new builds unless someone takes care of the Mac OS build or I get enough donation for a new device.

You are welcome taking a try and I look forward to your feedback. Please visit the dev branch for detail.

**Comment by caoccao** [comment]
The x86_64 version is published.

**Comment by caoccao** [comment]
The arm64 version is supported.
