### ISSUE TITLE
How to require a third-party library？

### ISSUE THREAD

**Issue by Aricgit** [caoccao/Javet#33]
Report an error when introducing a third-party library

![image](https://user-images.githubusercontent.com/9571096/118218801-c5befc00-b4aa-11eb-8041-14cf1634d468.png)
![image](https://user-images.githubusercontent.com/9571096/118218813-cf486400-b4aa-11eb-9236-711e677636fb.png)

**Comment by caoccao** [comment]
That has been documented in this [link](https://github.com/caoccao/Javet/blob/main/docs/tutorial/modularization.rst#gaps-between-javet-nodejs-mode-and-native-nodejs). Basically, you need to create a dedicated folder hosting that script. That folder may stay with node_modules side by side so that Node.js can find node_modules.
