### ISSUE TITLE
maven module separation

### ISSUE THREAD

**Issue by Enrice** [caoccao/Javet#378]
I propose separating the maven modules (as is partly already done by "javet-core") as follows:
Provide a separate module for each combination of OS and architecture by "classifier" coordinate. The only module containing Java code would then be "javet-core".

**Comment by caoccao** [comment]
This is the decision that I've being thinking for long time, but haven't convinced myself on.

The current approach only requires one dependency. A one line config can exclude the duplicated code from 2+ dependencies.

The new approach requires at least 2 dependencies. That adds more work to the users and to me because I'll have to package all of them separately. As the release publishing process is not completely automated, I'll spend 2x-3x more time on that. Please consider I've been doing that for free for many years.

**Comment by Enrice** [comment]
Thank you.
Full publishing automation would be of great help for yourself of course.

Don't get me wrong: I highly appreciate your great work!

I will consider implementing your proposal in our CI/CD pipeline.

**Comment by caoccao** [comment]
Thank you.

Some other users also tweak their CI/CD systems this way.

Complete automation currently is impossible for me.

1. Some OS / CPU Arch require special build env and process that github doesn't support.
2. I don't have the resource to set up everything locally.

**Comment by caoccao** [comment]
It has come to the reality since v4.
