### ISSUE TITLE
Unloading library - V8

### ISSUE THREAD

**Issue by Vshnv** [caoccao/Javet#45]
**Description:** 
We are using the library in an "extension" application which could possibly be reloaded when the user wants. 

But this seems to cause issues since the native library remains loaded on the old classloader.  

Is there possibly any concise way provided to properly stop or unload the library? 
I have tried to remove all references to the classloader that loads javet and classes loaded by that classloader, but it seems calling gc and runFinalization still doesnt unload the library/classloader.

**Comment by caoccao** [comment]
The Javet implementation is compatible with unloading the library, but I decided not to expose that capability.

Performance
---

Loading the library has to be single threaded which requires singleton pattern to be in place. That is how Javet loads Node.js instance. However, that comes with a noticeable performance overhead because Javet has to a) deploy 10-30MB binary to temp directory; b) load that 10-30MB binary to JVM; 3) initialize the instance.

To get rid of that overhead, Javet builds in the V8 instance and disallows the library to be unloaded.

Suggestion
---

You may load Javet in a new classloader. Once that classloader becomes orphan, JVM will unload Javet.

**Comment by Vshnv** [comment]
I actually am already loading javet onto a separate classloader. I tried removing all references and trying to force gc, it seems to not be able to release the classloader altho there are no references to anything loaded by it or the classloader itself held in the application. 
The only library being loaded in the isolated classloader is javet.
Do you have any ideas on whether this might be due to javet? Like by shutdown hooks or similar that can leak its reference?

**Comment by caoccao** [comment]
Node.js is not designed to be reloaded. I'm trying to hack it.

V8 seems to be compatible with that. I'm testing it.

Please stay tuned. It may come true in the next release. In the meanwhile, if you could post you PoC code, that would be very helpful.

**Comment by Vshnv** [comment]
Alright. Thats great. Ill send you the PoC in the morning.

**Comment by caoccao** [comment]
Good news. That feature is included in this [commit](https://github.com/caoccao/Javet/commit/40ce78afb413a7dc29efb9217c6d2b4bbca4baf8). Please wait for the next release.

**Comment by Vshnv** [comment]
Oh, that's awesome! Is there any ETA for the next release?

Also, yea sure, Ill check out that discussion.

**Comment by caoccao** [comment]
I plan to release it next week.

**Comment by Vshnv** [comment]
Would a earlier patch release be possible? A week might really push our timeline

**Comment by caoccao** [comment]
Next Monday is public holiday, how about next Tuesday?

**Comment by Vshnv** [comment]
Oh I see. Alrighty. Thank you.

**Comment by Vshnv** [comment]
Thank you!
