### ISSUE TITLE
JVM crash in libjavet-node-windows-x86_64.v.0.9.9.dll

### ISSUE THREAD

**Issue by gordhosted** [caoccao/Javet#82]
getting the following crash when running a js file using node instance, error log is attached

--
A fatal error has been detected by the Java Runtime Environment:

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff82a2244c6, pid=23196, tid=0x0000000000005490

JRE version: OpenJDK Runtime Environment (8.0_302-b08) (build 1.8.0_302-b08)
Java VM: OpenJDK 64-Bit Server VM (25.302-b08 mixed mode windows-amd64 compressed oops)
Problematic frame:
C  [libjavet-node-windows-x86_64.v.0.9.9.dll+0x844c6]
--

full details in attachment

[hs_err_pid17384.log](https://github.com/caoccao/Javet/files/7069441/hs_err_pid17384.log)

**Comment by gordhosted** [comment]
the issue seems to be setting the "File" object, take that line out and no issue
```
try (V8Runtime v8Runtime = V8Host.getNodeInstance().createV8Runtime())
{
	v8Runtime.setConverter(new JavetProxyConverter());

	v8Runtime.getGlobalObject().set("File", java.io.File.class);

	String s = "var AWS = require('aws-sdk'); var ec2 = new AWS.EC2();";

	v8Runtime.getExecutor(s).executeVoid();
			
	v8Runtime.getGlobalObject().delete("File");
}

```

**Comment by caoccao** [comment]
> the issue seems to be setting the "File" object, take that line out and no issue

So the issue is resolved, right? Mixing Node.js modules with Java objects is kind of dangerous because neither side expects seeing alien things, until Javet is able to mix them up.

**Comment by gordhosted** [comment]
i can close this if you want but i'd like to understand why a jvm crash occurs instead of a properly handled error/exception? it's one thing to have an exception logged and your main application keeps running, it's another when it crashes due to a rather safe looking line of code being used (setting a single global object to a static class)

replacing the offending line from above with the following and the jvm **does not** crash:

`v8Runtime.getGlobalObject().set("Java", java.io.File.class);`

this hints at a naming conflict somewhere in aws-sdk (or elsewhere) that isn't handled properly. it also suggests a good idea might be to use the Java.type() pattern mooted in https://github.com/caoccao/Javet/discussions/84

that would in theory avoid naming any conflicts since graalvm is a standard and everyone knows they use "Java". at the least please consider including a warning that setting global objects can cause issues. i don't see any easy way to have known in advance that setting a "File" variable would cause such mayhem :)

thanks

**Comment by gordhosted** [comment]
also the debug log attached shows the error to happen in the close() methods of V8Runtime and V8Native, very likely the crash occurs after the script has already finished?

```
com.caoccao.javet.interop.V8Native.closeV8Runtime(J)V+0
j  com.caoccao.javet.interop.V8Host.closeV8Runtime(Lcom/caoccao/javet/interop/V8Runtime;)V+42
j  com.caoccao.javet.interop.V8Runtime.close(Z)V+22
j  com.caoccao.javet.interop.V8Runtime.close()V+13
```

maybe there is a cleanup issue somewhere, doesn't make sense to crash in a close() method

**Comment by caoccao** [comment]
Good point!

That's a typical pitfall I think Java developers may easily fall into.

# What Happens Here?

The root cause is everything is in global context. That increases the possibility of getting conflicts. When multiple native implementations cross each other, nasty thing (crash) happens. It is similar to loading multiple JS libraries in a browser. Some libraries may register `$` for special use, e.g. jQuery. Only the last one wins the battle. So jQuery has to fall back to `jQuery`.

Why doesn't Javet catch the crash? Because of **Performance**. Javet could surround every call with try-catch, however, that would bring down the performance of all regular calls. If the code is properly written, application shall not pay this kind of performance overhead. So, Javet doesn't prevent this kind of crash from taking place.

# What is the Javet Recommended Way?

The recommended way is to use ES6 modules to enforce the segregation of native implementations.

In your case, you may:

1. Inject `File` in module A that deals with Java objects and host AWS SDK in module B.
2. Expose module A and B in global context and let them interact with each other.

Thus, the `File` in module B is the Node.js native implementation and there's no crash at all. Javet gives fantastic support to intercept the module resolution process. It can even alter how Node.js resolves modules. Please refer to this [doc](https://github.com/caoccao/Javet/blob/main/docs/reference/modularization.rst) for more details.

---

By the way, you are welcome joining the [discord](https://discord.gg/R4vvKU96gw) to discuss with me in detail.

**Comment by caoccao** [comment]
> maybe there is a cleanup issue somewhere, doesn't make sense to crash in a close() method

Yes, Javet is responsible for cleaning up the V8 runtime to prevent memory leak. But if multiple native modules messed up the memory, crash would be inevitable. In this case, [Fail-fast](https://en.wikipedia.org/wiki/Fail-fast) is the way that Javet follows. Hiding the errors would be more harmful, I suppose, because the errors would accumulate and result in JVM OOM in production.

Hope that makes sense. Please let me know if you have any questions.

**Comment by gordhosted** [comment]
i will close this but i have to respectfully disagree with @caoccao . javet is a library used to launch node scripts from within a running jvm. when javet is done the jvm should still be running :)

in an enterprise or production setting you simply cannot have a jvm crash, end of story. imagine if you launched a java context from graalvm with some global bindings and it crashed the jvm during execution, this would certainly be fixed. safety checks should be possible to avoid a crash at least at the highest level. i also don't see how OOM would occur necessarily, but i'm not an expert in the internals of the V8 runtime.

i'm going to add a feature request for adding some high level try/catch blocks as an option when creating the V8Runtime. useful for enterprise workloads that can't have jvm crashes even if it means slower "performance". and on the plus side we have a simple test case if it gets implemented :) thanks

**Comment by gordhosted** [comment]
too curious so i did a quick check to see if graalvm has issues running what to me is really the same code, **no jvm crash** and using their experimental commonjs support. interesting.

main.java
```
Map<String, String> options = new HashMap<>();

options.put("js.commonjs-require", "true");
options.put("js.commonjs-require-cwd", "C:\\node-v14.17.5-win-x64");
options.put("js.commonjs-global-properties", "./globals.js");
options.put("js.commonjs-core-modules-replacements", "buffer:buffer/,os:os-browserify," + "path:path-browserify," + "crypto:crypto-browserify");

try (Context context = Context.newBuilder().allowExperimentalOptions(true).allowAllAccess(true).allowIO(true).options(options).build())
{
	context.getBindings("js").putMember("File", java.io.File.class);

	String s = "var AWS = require('aws-sdk'); var ec2 = new AWS.EC2(); console.log(File);";
	Source source = Source.newBuilder("js", s, "index.mjs").build();

	context.eval(source);
	
	Value jsBindings = context.getBindings("js");

	System.out.println(context.getBindings("js").getMemberKeys());
}
```
console output:
```
C:\node-v14.17.5-win-x64\.
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[engine] WARNING: The polyglot context is using an implementation that does not support runtime compilation.
The guest application code will therefore be executed in interpreted mode only.
Execution only in interpreted mode will strongly impact the guest application performance.
For more information on using GraalVM see https://www.graalvm.org/java/quickstart/.
To disable this warning the '--engine.WarnInterpreterOnly=false' option or use the '-Dpolyglot.engine.WarnInterpreterOnly=false' system property.
class java.io.File
[process, Buffer, global, System, File]
```

again, from my point of view this issue is still leaving me a bit concerned. i'd also like to know if the sample code crashes on linux or just windows (my guess - windows only). i'll reopen in case @caoccao wants to add a comment.

**Comment by caoccao** [comment]
No problem. I will look into it later as long as I can reproduce the issue.

Please keep this issue open.

**Comment by caoccao** [comment]
I think you didn't specify the working directory and require root directory. Node.js is not prepared for running code string without these info. I don't meet the issue you reported with the following test.

# Directory Structure

```
java-application-root-path
└─scripts
   └─node
       ├─node_modules
       │  └─aws-sdk
       └─test-aws-sdk
               test-aws-sdk.js
```

# test-aws-sdk.js

```js
const AWS = require('aws-sdk');
const ec2 = new AWS.EC2();
console.log('done');
```

# TestAWSSDK.java

```java
public class TestAWSSDK {
    public static void main(String[] args) throws JavetException {
        try (V8Runtime v8Runtime = V8Host.getNodeInstance().createV8Runtime()) {
            v8Runtime.setConverter(new JavetProxyConverter());
            v8Runtime.getGlobalObject().set("File", java.io.File.class);
            Path codePath = Path.of(JavetOSUtils.WORKING_DIRECTORY)
                    .resolve("scripts/node/test-aws-sdk/test-aws-sdk.js");
            v8Runtime.getExecutor(codePath).executeVoid();
            v8Runtime.getGlobalObject().delete("File");
            v8Runtime.lowMemoryNotification();
        }
    }
}
```

It works pretty well.

What's the difference? In Javet, `V8PathExecutor` calls `setResourceName()` to tell Node.js the following important things.

* `__dirname`
* `__filename`
* Require root directory
* Working directory

Thus, Node.js is able to proceed. That is well documented at [here](https://github.com/caoccao/Javet/blob/main/docs/reference/modularization.rst).

---

By the way, Javet is growing up and needs to leave good reputation outside. So far, most of the issues folks meet come from improper use of the API, lack of documentation, features not implemented, not being thinking in Javet, I'd recommend discussing the issues here instead of posting frustration outside firstly. Please let me know if you have any questions.

Thank you.

**Comment by gordhosted** [comment]
i copied your example code i didn't know it was incomplete. please consider updating it as follows to save future problems for others

```
// Node.js Mode
try (V8Runtime v8Runtime = V8Host.getNodeInstance().createV8Runtime()) {
  // Set the require root directory so that Node.js is able to locate node_modules or your JVM will crash
  ...

  // now you can safely execute
  System.out.println(v8Runtime.getExecutor("'Hello Javet'").executeString());
}
```
also, your example reference in the docs does not compile and has at least two errors. can you please post a proper example that compiles and works. getNodeModuleModule() is not a method in V8Runtime (i'm on v0.9.9), how do you get a reference to NodeModuleModule?

i am executing with a String, not pointing to a file as your example above so can't use that code, thanks
```
try (JavetEnginePool<NodeRuntime> javetEnginePool = new JavetEnginePool<NodeRuntime>()) {
    javetEnginePool.getConfig().setJSRuntimeType(JSRuntimeType.Node);
    try (IJavetEngine<NodeRuntime> javetEngine = javetEnginePool.getEngine()) {
        NodeRuntime nodeRuntime = iJavetEngine.getV8Runtime();  // ERROR should be javetEngine
        Path workingDirectory = new File(JavetOSUtils.WORKING_DIRECTORY, "scripts/node/test-node").toPath();
        // Set the require root directory so that Node.js is able to locate node_modules.
        nodeRuntime.getNodeModuleModule().setRequireRootDirectory(workingDirectory);  // ERROR method getNodeModuleModule() does not exist
        getLogger().logInfo("1.23 + 2.34 = {0}", nodeRuntime.getExecutor(
                "const Decimal = require('decimal.js');" +
                        "const a = new Decimal(1.23);" +
                        "const b = new Decimal(2.34);" +
                        "a.add(b).toString();").executeString());
    }
}
```

**Comment by caoccao** [comment]
Nice catch. I have to admit that's a problem of my maintaining everything while developing new features or refactoring existing features. I just updated the doc as you pointed out. Thank you.

By the way, the AWS SDK issue is resolved, right? If YES, I'm happy to see you may proceed with your automation project.

In fact, my expectation is: Javet is an open-source project. If the document is out of date, pull requests are welcome. Holding high expectation on my fixing all of them would less likely be realistic because my priority is driven more by quality, security, features. I hope Javet will be more of a community driven project instead of a personal one.

Hope that makes sense. Please let me know if you have any questions.

**Comment by gordhosted** [comment]
i can run my code just fine WITHOUT setting the root directory so that was not problem. the problem is the missing lowMemoryNotification() method call that seems required IFF i call delete() from the global object.

example 1 - this works, no jvm crash
```
try (V8Runtime v8Runtime = V8Host.getNodeInstance().createV8Runtime())
{
	v8Runtime.setConverter(new JavetProxyConverter());

	v8Runtime.getGlobalObject().set("File", java.io.File.class);

	String s = "var AWS = require('aws-sdk'); var ec2 = new AWS.EC2(); console.log(ec2)";

	v8Runtime.getExecutor(s).executeVoid();

	v8Runtime.getGlobalObject().delete("File");

	v8Runtime.lowMemoryNotification();
}
```
example 2 - this crashes jvm, missing lowMemoryNotification()
```
try (V8Runtime v8Runtime = V8Host.getNodeInstance().createV8Runtime())
{
	v8Runtime.setConverter(new JavetProxyConverter());

	v8Runtime.getGlobalObject().set("File", java.io.File.class);

	String s = "var AWS = require('aws-sdk'); var ec2 = new AWS.EC2(); console.log(ec2)";

	v8Runtime.getExecutor(s).executeVoid();

	v8Runtime.getGlobalObject().delete("File");

//	v8Runtime.lowMemoryNotification();
}
```
example 3 - this works, no delete() call to global object therefore no lowMemoryNotification() call needed?
```
try (V8Runtime v8Runtime = V8Host.getNodeInstance().createV8Runtime())
{
	v8Runtime.setConverter(new JavetProxyConverter());

	v8Runtime.getGlobalObject().set("File", java.io.File.class);

	String s = "var AWS = require('aws-sdk'); var ec2 = new AWS.EC2(); console.log(ec2)";

	v8Runtime.getExecutor(s).executeVoid();

//	v8Runtime.getGlobalObject().delete("File");

//	v8Runtime.lowMemoryNotification();
}
```
it appears that if you delete something from the global object you have to call lowMemoryNotification(). @caoccao can you explain a bit more why it is required i don't see any docs on it, looks like a native method, thanks

**Comment by gordhosted** [comment]
i also see the following in JavetEngine which hints that we are supposed to call lowMemoryNotification() before a close
```
protected void close(boolean forceClose) throws JavetException {
    setActive(false);
    if (forceClose) {
        if (iJavetEnginePool.getConfig().isGcBeforeEngineClose()) {
            v8Runtime.lowMemoryNotification();
        }
        v8Runtime.close(true);
    } else {
        iJavetEnginePool.releaseEngine(this);
    }
}
```

**Comment by caoccao** [comment]
Nice observation. That was explained in #20.

It's a Node.js specific behavior because Node.js has its own event loop (libuv). **Its event loop actually is activated when Node.js is exiting.** Not many Node.js developers know that. Once Node.js is exiting, Javet has already completed the `close()`. Boom, coredump. In case there are unhandled events, `await()` or `lowMemoryNotification()` needs to be called explicitly. There is no easy way of patching that because patching implies changing Node.js behavior which is not what I want to do. I believe the genuine Node.js is what people want. Please refer to this [doc](https://github.com/caoccao/Javet/blob/main/docs/tutorial/interact_with_node_js.rst) for more details.

As Javet is compatible with both Node.js mode and V8 mode, it has to keep the door open to both of them. That's reflected by the code in the engine you posted.

**Comment by gordhosted** [comment]
ok i will just add the extra method call then, thanks

**Comment by caoccao** [comment]
> ok i will just add the extra method call then, thanks

To be clear, this is only required if JavetProxyConverter is in use, or there are dangling interceptors not recycled. In most of the cases, there's no need to do that.

**Comment by caoccao** [comment]
Here is the detailed [explanation](https://www.caoccao.com/Javet/faq/troubleshooting/why_node_js_crashes_when_being_closed.html).

**Comment by caoccao** [comment]
Update: From v0.9.12, this special case will not cause JVM crash.
